apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge-monolith  
  labels:
    app: tech-challenge-monolith
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tech-challenge-monolith
  template:
    metadata:
      labels:
        app: tech-challenge-monolith
    spec:
      containers:
        - name: tech-challenge-monolith
          image: luizpainodev/tech-challenge-monolith:latest
          ports:
            - containerPort: 4000
          envFrom:
          - configMapRef:
              name: tech-challenge-config
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"      
