apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-service
  labels:
    app: tech-challenge-monolith
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"  # Define que o LoadBalancer será interno (privado)
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # Usando Network Load Balancer (ALB também pode ser usado)
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "TCP"  # Protocolo usado
    service.beta.kubernetes.io/aws-load-balancer-arn: "arn:aws:elasticloadbalancing:us-east-1:217399333134:loadbalancer/net/tech-challenge-nlb/9f742850fb16b12e"
spec:
  type: LoadBalancer  
  selector:
    app: tech-challenge-monolith
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4000
  externalTrafficPolicy: Cluster