apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-monolith
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-security-groups: "eks_sg"
spec:
  type: LoadBalancer
  selector:
    app: tech-challenge-monolith
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  loadBalancerSourceRanges:
    - "0.0.0.0/0"