apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-service
  labels:
    app: tech-challenge-monolith
spec:
  type: LoadBalancer
  ports:
    - port: 80            # Porta externa para o load balancer
      targetPort: 80    # Porta interna que seu contêiner está escutando
  selector:
    app: tech-challenge-monolith  # Deve corresponder às labels do Pod